# Generated by Django 2.2.12 on 2020-09-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0002_auto_20200905_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageOutputConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Imagen consumible',
                'verbose_name_plural': 'Imagen de consumibles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='typemodelconsumable',
            name='voltage_ouput_typeConsumable',
        ),
        migrations.AddField(
            model_name='typemodelconsumable',
            name='VoltageOutput_typeConsumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumable.VoltageOutputConsumable'),
        ),
    ]
