# Generated by Django 2.2.12 on 2020-09-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0003_auto_20200905_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voltageoutputconsumable',
            options={'ordering': ['name'], 'verbose_name': 'Voltage output', 'verbose_name_plural': 'Voltages output'},
        ),
    ]
