# Generated by Django 2.2.12 on 2020-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='image_installation',
            field=models.ManyToManyField(blank=True, to='installation.ImageInstallation'),
        ),
    ]
