# Generated by Django 2.2.12 on 2020-08-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20200824_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='image_installation',
            field=models.ManyToManyField(to='installation.ImageInstallation'),
        ),
    ]
