# Generated by Django 2.2.12 on 2020-09-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20200905_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_docInstallation', models.CharField(max_length=50, verbose_name='Nombre')),
                ('url_docInstallation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Archivo instalación',
                'verbose_name_plural': 'Archivos de instalación',
                'ordering': ['name_docInstallation'],
            },
        ),
        migrations.AddField(
            model_name='installation',
            name='doc_installation',
            field=models.ManyToManyField(blank=True, to='installation.DocInstallation'),
        ),
    ]
