# Generated by Django 2.2.16 on 2020-09-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0011_auto_20200917_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preventive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_preventive', models.CharField(max_length=10, verbose_name='Código preventive')),
                ('startDatetime_preventive', models.DateTimeField(blank=True, null=True, verbose_name='FechaIncidencia')),
                ('observations_preventive', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('station_preventive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
            ],
            options={
                'verbose_name': 'Mant Preventivo',
                'verbose_name_plural': 'Mant Preventivos',
                'ordering': ['code_preventive'],
            },
        ),
    ]
