# Generated by Django 2.2.16 on 2020-09-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPreventive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDatetime_partPreventive', models.DateTimeField(blank=True, null=True, verbose_name='FechaIncidencia')),
                ('station_partPreventive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preventive.Preventive')),
            ],
            options={
                'verbose_name': 'Parte Preventiva',
                'verbose_name_plural': 'Partes Preventivas',
                'ordering': ['id'],
            },
        ),
    ]
