# Generated by Django 2.2.16 on 2020-09-22 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0002_partpreventive'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPreventive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_statusPreventive', models.CharField(max_length=30, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado del preventivo',
                'verbose_name_plural': 'Estados del preventivo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='preventive',
            name='status_preventive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preventive.StatusPreventive'),
        ),
    ]
