# Generated by Django 2.2.16 on 2020-09-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0006_partname_acronym_partname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partname',
            name='name_partName',
            field=models.CharField(max_length=40, verbose_name='nombre'),
        ),
    ]
