# Generated by Django 2.2.16 on 2020-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0008_auto_20200924_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='autDIandAIinCCStatus_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ED y EA que puedan estar dudosas en CC'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='autHardwareDiagnosis_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Diagnóstico de Hardware'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='autLithiumBatteryStatus_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado de batería de litio'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='autVisualInspectionOfAlarmLedStatus_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Inspección estado alarmas de Led'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='autcheckRxTxOnCommunicationCards_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Comprobar Rx yTx en tarjetas de comunicaciones'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='endDatetime_preventive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha finalización Preventivo'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='gencleaningVentilationFilters_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Limpieza de filtros de ventilación'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='genelementCleaning_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Limpieza de elementos'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='genfreeOfCorrosion_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Libre de corrosión'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='genupdatedSignalList_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Lista de señales actualizada'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='genventilationSystemAndThermostat_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Sistema de ventilación y termostato'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='saibatteryStatus_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado de las baterías'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='saicleaning_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Limpieza, si procede'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='saiinputVoltageMeasurement_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Medida de tensión de entrada'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='saioutputVoltageToConsumption_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Comprobar tensión de salida a consumo'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='saistatusOfConnectorsAndLEDs_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado de conectores y Leds'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='startDatetime_preventive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='FechaComienzo Preventivo'),
        ),
        migrations.DeleteModel(
            name='PartPreventive',
        ),
    ]
