# Generated by Django 2.2.16 on 2020-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0009_auto_20200924_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPreventive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualPreventiveContract_ContractPreventive', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de preventivos en contrato')),
            ],
            options={
                'verbose_name': 'Contrato mantenimiento preventivo',
                'verbose_name_plural': 'contratos mantenimientos preventivos',
                'ordering': ['annualPreventiveContract_ContractPreventive'],
            },
        ),
    ]
