# Generated by Django 2.2.16 on 2020-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0010_contractpreventive'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractedCompanyPreventive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contractedCompanyPrevent', models.IntegerField(blank=True, null=True, verbose_name='Nombre empresa contratada Mant Preventivo')),
            ],
            options={
                'verbose_name': 'Empresa contratada mantenimiento preventivo',
                'verbose_name_plural': 'Empresas contratadas mantenimiento preventivo',
                'ordering': ['name_contractedCompanyPrevent'],
            },
        ),
    ]
