# Generated by Django 2.2.16 on 2020-10-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0014_auto_20201002_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive',
            old_name='autLithiumBatteryStatus_preventiveDetail_preventive',
            new_name='autLithiumBatteryStatusNoOkDetail_preventive',
        ),
        migrations.AddField(
            model_name='preventive',
            name='autHardwareDiagnosisNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Diagnóstico de Hardware'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autHardwareDiagnosis_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], max_length=40, null=True, verbose_name='Diagnóstico de Hardware'),
        ),
    ]
