# Generated by Django 2.2.16 on 2020-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0016_auto_20201002_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='autLithiumBatteryNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaciones estado de baterías de litio'),
        ),
    ]
