# Generated by Django 2.2.16 on 2020-10-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0017_preventive_autlithiumbatterynookdetail_preventive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive',
            old_name='autLithiumBatteryNoOkDetail_preventive',
            new_name='autLithiumBatteryStatusNoOkDetail_preventive',
        ),
    ]
