# Generated by Django 2.2.16 on 2020-10-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0018_auto_20201002_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='autDIandAIinCCStatusNoOkDetail_preventive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Observaciones ED y EA que puedan estar dudosas en CC'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autDIandAIinCCStatus_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='ED y EA que puedan estar dudosas en CC'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autVisualInspectionOfAlarmLedStatus_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=20, null=True, verbose_name='Estado de LEDs de alarma'),
        ),
    ]
