# Generated by Django 2.2.16 on 2020-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0019_auto_20201002_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventive',
            name='autDIandAIinCCStatusNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Observaciones ED y EA que puedan estar dudosas en CC'),
        ),
    ]
