# Generated by Django 2.2.16 on 2020-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0020_auto_20201002_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='autcheckRxTxOnCommunicationCardsNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Observaciones comprobar Rx yTx en tarjetas de comunicaciones'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autcheckRxTxOnCommunicationCards_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Comprobar Rx yTx en tarjetas de comunicaciones'),
        ),
    ]
