# Generated by Django 2.2.16 on 2020-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0021_auto_20201002_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='genventilationSystemAndThermostatNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones sistema de ventilación y termostato'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autDIandAIinCCStatusNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones ED y EA que puedan estar dudosas en CC'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autHardwareDiagnosisNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones diagnóstico de Hardware'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autLithiumBatteryStatusNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones estado de baterías de litio'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autVisualInspectionOfAlarmLedStatusNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones estado de LEDs de alarma'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='autcheckRxTxOnCommunicationCardsNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones comprobar Rx yTx en tarjetas de comunicaciones'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='genventilationSystemAndThermostat_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Sistema de ventilación y termostato'),
        ),
    ]
