# Generated by Django 2.2.16 on 2020-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0024_auto_20201002_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='genelementCleaningNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones limpieza de elementos'),
        ),
        migrations.AddField(
            model_name='preventive',
            name='genupdatedSignalListNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones lista de señales actualizada'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='genelementCleaning_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Limpieza de elementos'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='genupdatedSignalList_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Lista de señales actualizada'),
        ),
    ]
