# Generated by Django 2.2.16 on 2020-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0026_auto_20201002_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='saibatteryStatus_preventiveNoOkDetail',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones estado de las baterías'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='saibatteryStatus_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Estado de las baterías'),
        ),
    ]
