# Generated by Django 2.2.16 on 2020-10-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0027_auto_20201002_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive',
            old_name='saibatteryStatus_preventiveNoOkDetail',
            new_name='saibatteryStatusNoOkDetail_preventive',
        ),
    ]
