# Generated by Django 2.2.16 on 2020-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0028_auto_20201002_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='saicleaningNoOkDetail_preventive',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones limpieza, si procede'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='saicleaning_preventive',
            field=models.CharField(blank=True, choices=[('1', 'OK'), ('2', 'No OK'), ('3', 'NP')], default='1', max_length=40, null=True, verbose_name='Limpieza, si procede'),
        ),
    ]
