# Generated by Django 2.2.16 on 2020-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0030_auto_20201002_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='totalEstimatedTime',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Tiempo estimado minutos'),
        ),
    ]
