# Generated by Django 2.2.16 on 2020-10-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0032_auto_20201007_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventive',
            old_name='totalEstimatedTime',
            new_name='totalEstimatedTime_preventive',
        ),
    ]
