# Generated by Django 2.2.16 on 2020-10-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_user_employee'),
        ('preventive', '0033_auto_20201007_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventive',
            name='employee_preventive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
