# Generated by Django 2.2.16 on 2020-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0035_auto_20201015_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventive',
            name='employee_preventive',
            field=models.ManyToManyField(limit_choices_to={'name_company': 'Suez Environment'}, related_name='preventives', to='employee.Employee'),
        ),
    ]
