# Generated by Django 2.2.16 on 2020-10-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0036_auto_20201015_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractedcompanypreventive',
            name='name_contractedCompanyPrevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='preventive',
            name='employee_preventive',
            field=models.ManyToManyField(related_name='preventives', to='employee.Employee'),
        ),
    ]
