# Generated by Django 2.2.12 on 2020-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=50, verbose_name='Localidad')),
                ('longitude_conf_map', models.CharField(max_length=20, verbose_name='longitud')),
                ('latitude_conf_map', models.CharField(max_length=20, verbose_name='latitud')),
                ('zoom_conf_map', models.CharField(max_length=20, verbose_name='zoom')),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
                'ordering': ['name_location'],
            },
        ),
    ]
