# Generated by Django 2.2.12 on 2020-08-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social_network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre red social')),
                ('address_social_network', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección red social')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='web_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección web'),
        ),
    ]
