# Generated by Django 2.2.12 on 2020-08-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200814_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_file_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre archivo imagen'),
        ),
    ]
