# Generated by Django 2.2.16 on 2020-11-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0002_address_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='contact_Address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_Address',
        ),
    ]
