# Generated by Django 2.2.16 on 2020-11-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0003_auto_20201101_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
