# Generated by Django 2.2.16 on 2020-11-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0006_auto_20201101_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_CA', models.CharField(blank=True, max_length=20, null=True, verbose_name='Administrador de fincas')),
                ('address_CA', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección')),
                ('phone1_CA', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono1')),
                ('phone2_CA', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono2')),
                ('email_CA', models.EmailField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('info_CA', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Administrador de Fincas',
                'verbose_name_plural': 'Administradores de Fincas',
                'ordering': ['name_CA'],
            },
        ),
    ]
