# Generated by Django 2.2.16 on 2020-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0007_communityagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityagency',
            name='address_CA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
    ]
