# Generated by Django 2.2.16 on 2020-11-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0008_auto_20201101_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='communityAgency',
            field=models.ManyToManyField(to='streetMap.CommunityAgency'),
        ),
    ]
