# Generated by Django 2.2.16 on 2020-11-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0009_address_communityagency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='communityAgency',
            new_name='communityAgency_Address',
        ),
    ]
