# Generated by Django 2.2.12 on 2020-09-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTechnologyStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Acrónimo')),
                ('acronym', models.CharField(max_length=20, verbose_name='Significado')),
                ('url', models.CharField(max_length=150, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Tecnología de comunicación',
                'verbose_name_plural': 'Tecnologías de comunicación',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='typestation',
            options={'verbose_name': 'Tipo estación', 'verbose_name_plural': 'Tipos de estaciones'},
        ),
        migrations.AddField(
            model_name='station',
            name='communication_windows_station',
            field=models.TextField(blank=True, null=True, verbose_name='ventana de comunicación'),
        ),
        migrations.AlterField(
            model_name='station',
            name='image_station',
            field=models.ManyToManyField(blank=True, to='station.ImageStation'),
        ),
        migrations.AlterField(
            model_name='typestation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tipo estación'),
        ),
        migrations.AddField(
            model_name='station',
            name='communication_technology_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.CommunicationTechnologyStation'),
        ),
    ]
