# Generated by Django 2.2.12 on 2020-08-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='timestamp_station',
        ),
    ]
