# Generated by Django 2.2.12 on 2020-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='image_station',
            field=models.ManyToManyField(blank=True, to='station.ImageStation'),
        ),
    ]
