# Generated by Django 2.2.12 on 2020-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20200824_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='type_station',
            field=models.CharField(blank=True, choices=[('0', '-----'), ('1', 'EBAR'), ('2', 'EBAP'), ('3', 'RDAP'), ('4', 'ESAP'), ('5', 'DRAP'), ('6', 'ECS'), ('7', 'EDAR'), ('8', 'DDAP'), ('9', 'PLVM'), ('10', 'CC'), ('11', 'REP'), ('12', 'OTROS')], default=0, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='TypeStation',
        ),
    ]
