# Generated by Django 2.2.12 on 2020-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_remove_station_timestamp_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='areastation',
            name='color_background',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color HTML'),
        ),
    ]
