# Generated by Django 2.2.12 on 2020-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20200828_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='communication_technology_station',
            field=models.CharField(blank=True, choices=[('0', 'RADIOFRECUENCIA'), ('1', 'SMS'), ('2', 'GSM'), ('3', 'FIBRA ÓPTICA'), ('4', 'OTROS')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='type_station',
            field=models.CharField(blank=True, choices=[('0', 'EBAR'), ('1', 'EBAP'), ('2', 'RDAP'), ('3', 'ESAP'), ('4', 'DRAP'), ('5', 'ECS'), ('6', 'EDAR'), ('7', 'DDAP'), ('8', 'PLVM'), ('9', 'CC'), ('10', 'REP'), ('11', 'OTROS')], default=0, max_length=2, null=True),
        ),
    ]
