# Generated by Django 2.2.12 on 2020-09-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_auto_20200905_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Descripción de url')),
                ('url', models.TextField(blank=True, max_length=500, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='video_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.VideoStation'),
        ),
    ]
