# Generated by Django 2.2.12 on 2020-08-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_areastation_color_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areastation',
            old_name='color_background',
            new_name='color_html_background',
        ),
    ]
