# Generated by Django 2.2.12 on 2020-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20200902_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='communication_windows_station',
            field=models.TextField(blank=True, null=True, verbose_name='ventana de comunicación'),
        ),
    ]
