# Generated by Django 2.2.12 on 2020-09-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_auto_20200910_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='video_station',
            field=models.ManyToManyField(blank=True, to='station.VideoStation'),
        ),
    ]
