# Generated by Django 2.2.12 on 2020-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_auto_20200910_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_docStation', models.CharField(max_length=50, verbose_name='Nombre')),
                ('url_docStation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Doc estación',
                'verbose_name_plural': 'Doc de estaciones',
                'ordering': ['name_docStation'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='doc_station',
            field=models.ManyToManyField(blank=True, to='station.DocStation'),
        ),
    ]
