# Generated by Django 2.2.12 on 2020-09-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0009_auto_20200910_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='communication_technology_station',
            field=models.ForeignKey(blank=True, db_column='Tecnología de comunicación', null=True, on_delete=django.db.models.deletion.CASCADE, to='station.CommunicationTechnologyStation'),
        ),
    ]
