# Generated by Django 2.2.12 on 2020-08-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIncidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de incidencia')),
                ('color_html_background', models.CharField(max_length=20, verbose_name='Color fondo html incluir #')),
            ],
            options={
                'verbose_name': 'Estado de incidencia',
                'verbose_name_plural': 'Estados de incidencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeIncidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de incidencia')),
                ('color_html_background', models.CharField(max_length=20, verbose_name='Color fondo html incluir #')),
            ],
            options={
                'verbose_name': 'Tipo de incidencia',
                'verbose_name_plural': 'Tipos de incidencia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_incidence', models.DateTimeField(blank=True, null=True, verbose_name='FechaIncidencia')),
                ('observations_incidence', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('station_incidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
                ('statusIncidence_incidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidence.StatusIncidence')),
                ('typeIncidence_incidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidence.TypeIncidence')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['datetime_incidence'],
            },
        ),
    ]
