# Generated by Django 2.2.12 on 2020-09-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgencyLevelIncidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nivel de urgencia')),
                ('color_html_background', models.CharField(max_length=20, verbose_name='Color fondo html incluir #')),
            ],
            options={
                'verbose_name': 'Nivel de urgencia',
                'verbose_name_plural': 'Niveles de urgencia',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='incidence',
            name='urgencyLevel_incidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidence.UrgencyLevelIncidence'),
        ),
    ]
