# Generated by Django 2.2.16 on 2020-11-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0005_auto_20201105_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='repairForecast_incidence',
        ),
        migrations.AddField(
            model_name='repairforecast',
            name='incidence_RF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidence.Incidence'),
        ),
    ]
