# Generated by Django 2.2.16 on 2020-11-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('incidence', '0007_auto_20201105_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='companyRepair_incidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
