# Generated by Django 3.1.3 on 2020-11-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0008_incidence_companyrepair_incidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidence',
            options={'ordering': ['id'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
    ]
