# Generated by Django 3.1.3 on 2020-12-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0010_auto_20201204_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado facturación')),
            ],
            options={
                'verbose_name': 'Estado de facturación',
                'verbose_name_plural': 'Estados de facturación',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='incidence',
            name='invoiced_incidence',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='incidence',
            name='billing_incidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidence.billing'),
        ),
    ]
