# Generated by Django 3.1.3 on 2020-12-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0011_auto_20201204_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='html_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='HTML color'),
        ),
    ]
