# Generated by Django 3.1.3 on 2020-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0012_billing_html_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_conf',
            field=models.CharField(blank=True, choices=[('Envoiced', 'Envoiced'), ('Not envoiced', 'Not envoiced'), ('Not to envoice', 'Not to envoice')], max_length=20, null=True),
        ),
    ]
