# Generated by Django 3.1.3 on 2020-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0013_billing_billing_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusincidence',
            name='incidence_status_conf',
            field=models.CharField(blank=True, choices=[('In observation', 'In observation'), ('Partially repaired', 'Partially repaired'), ('Repared', 'Repared'), ('Without repair', 'Without repair'), ('Another', 'Another')], max_length=20, null=True),
        ),
    ]
