# Generated by Django 3.1.3 on 2021-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0014_statusincidence_incidence_status_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='anotherTypeIncidence_incidence',
            field=models.TextField(blank=True, null=True, verbose_name='Otro tipo de incidencia'),
        ),
    ]
