# Generated by Django 2.2.12 on 2020-09-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20200914_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodeldevice',
            name='doc_device',
        ),
        migrations.AddField(
            model_name='productmodeldevice',
            name='doc_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.DocDevice'),
        ),
    ]
