# Generated by Django 2.2.12 on 2020-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20200914_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodeldevice',
            name='doc_device',
        ),
        migrations.AddField(
            model_name='productmodeldevice',
            name='doc_device',
            field=models.ManyToManyField(blank=True, to='device.DocDevice'),
        ),
    ]
