# Generated by Django 2.2.12 on 2020-09-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200914_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdevice',
            name='url_docDevice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
    ]
