# Generated by Django 2.2.16 on 2020-10-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('vat_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de indentificación fiscal')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('description_email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
                'ordering': ['address_email'],
            },
        ),
    ]
