# Generated by Django 3.1.3 on 2020-12-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Compañía', 'verbose_name_plural': 'Compañías'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name_company',
            new_name='name',
        ),
    ]
