# Generated by Django 2.2.12 on 2020-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativoRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_AR', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('datetime_incidence', models.DateTimeField(blank=True, null=True, verbose_name='FechaRoa')),
                ('file_AR', models.FileField(max_length=254, upload_to=None)),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['number_AR'],
            },
        ),
    ]
