# Generated by Django 2.2.12 on 2020-10-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativorequirement',
            old_name='datetime_incidence',
            new_name='datetime_AR',
        ),
    ]
