# Generated by Django 2.2.12 on 2020-10-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0002_auto_20201031_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministrativoRequirement',
            new_name='AdministrativeRequirement',
        ),
    ]
