# Generated by Django 2.2.16 on 2020-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0003_auto_20201031_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_Address', models.CharField(max_length=20, verbose_name='Número calle')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['number_Address'],
            },
        ),
        migrations.AlterField(
            model_name='administrativerequirement',
            name='file_AR',
            field=models.FileField(upload_to='media/administrativeRequirement/'),
        ),
    ]
