# Generated by Django 2.2.16 on 2020-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0006_auto_20201101_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativerequirement',
            name='file_AR',
            field=models.FileField(upload_to='administrativeRequirement/'),
        ),
    ]
