# Generated by Django 2.2.16 on 2020-11-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0001_initial'),
        ('administrativeRequirement', '0007_auto_20201101_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streetMap.StreetMap'),
        ),
    ]
