# Generated by Django 2.2.16 on 2020-11-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0008_address_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativerequirement',
            name='address_AR',
            field=models.ManyToManyField(blank=True, null=True, to='administrativeRequirement.Address'),
        ),
    ]
