# Generated by Django 2.2.16 on 2020-11-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0010_auto_20201101_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativerequirement',
            name='address_AR',
        ),
    ]
