# Generated by Django 2.2.16 on 2020-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetMap', '0005_address_contact'),
        ('administrativeRequirement', '0011_remove_administrativerequirement_address_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativerequirement',
            name='address_AR',
            field=models.ManyToManyField(to='streetMap.Address'),
        ),
    ]
