# Generated by Django 2.2.16 on 2020-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0012_administrativerequirement_address_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativerequirement',
            name='observations_AR',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='administrativerequirement',
            name='reasonRequirement_AR',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Motivo requerimiento'),
        ),
    ]
