# Generated by Django 2.2.16 on 2020-11-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0013_auto_20201101_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Situación')),
                ('color_status', models.CharField(blank=True, max_length=12, null=True, verbose_name='HTML Color')),
            ],
            options={
                'verbose_name': 'Situación',
                'verbose_name_plural': 'Situaciones',
                'ordering': ['status'],
            },
        ),
        migrations.AddField(
            model_name='administrativerequirement',
            name='status_AR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativeRequirement.Status'),
        ),
    ]
