# Generated by Django 3.1.3 on 2020-11-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeRequirement', '0015_auto_20201101_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativerequirement',
            name='file_AR',
            field=models.FileField(blank=True, null=True, upload_to='administrativeRequirement/'),
        ),
    ]
