# Generated by Django 2.2.16 on 2020-10-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName1_employee', models.CharField(max_length=50, verbose_name='Apellido1')),
                ('lastName2_employee', models.CharField(max_length=50, verbose_name='Apellido2')),
                ('company_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['name_employee'],
            },
        ),
    ]
