# Generated by Django 2.2.16 on 2020-10-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='lastName1_employee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName2_employee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido2'),
        ),
    ]
